export const IPC = {
  STORE_GET: 'store:get',
  STORE_SET: 'store:set',
  STORE_DELETE: 'store:delete',
  STORE_ON_DID_CHANGE: 'store:onDidChange',
  FS_READ_FILE: 'fs:readFile',
  FS_WRITE_FILE: 'fs:writeFile',
  FS_DELETE_FILE: 'fs:deleteFile',
  FS_READ_DIR: 'fs:readDir',
  FS_EXISTS: 'fs:exists',
  FS_MKDIR: 'fs:mkdir',
  WINDOW_SET_SIZE: 'window:setSize',
  WINDOW_SET_POSITION: 'window:setPosition',
  WINDOW_GET_DISPLAY: 'window:getDisplay',
  WINDOW_GET_BOUNDS: 'window:getBounds',
  WINDOW_SET_BOUNDS: 'window:setBounds',
  WINDOW_SET_IGNORE_MOUSE_EVENTS: 'window:setIgnoreMouseEvents',
  WINDOW_MOVE_BY: 'window:moveBy',
  WINDOW_EXPAND_PANEL: 'window:expandPanel',
  WINDOW_COLLAPSE_PET: 'window:collapsePet',
  NOTIFICATION_SHOW: 'notification:show',
  DIALOG_OPEN_DIRECTORY: 'dialog:openDirectory',
  AUTOLAUNCH_ENABLE: 'autolaunch:enable',
  AUTOLAUNCH_DISABLE: 'autolaunch:disable',
  HOTKEY_QUICK_CAPTURE: 'hotkey:quickCapture',
} as const
